#!/bin/bash

measures='CE_TRAIN CE_VAL TRAIN_ACC VAL_ACC SOTL PATH_NORM PATH_NORM_OVER_EXPONENTIAL_MARGIN SPEC_INIT_MAIN_EXPONENTIAL_MARGIN FRO_DIST DIST_SPEC_INIT_FFT PACBAYES_INIT MAG_FLATNESS MAG_INIT SOTL'

for m in $measures; do
  sbatch -p small hpo.sh "$m" "cifar10"
done